### ISSUE TITLE
Made an adaptive icon

### ISSUE THREAD

**Issue by antoniacrespoa2** [JuniperPhoton/MyerSplash.Android#17]
If you would like to use, of course. Sent with source file in case you want to edit and polish it. 

[MyerSplash Adaptive Icon.zip](https://github.com/JuniperPhoton/MyerSplash.Android/files/3520837/MyerSplash.Adaptive.Icon.zip)

<img width="812" alt="Screenshot 2019-08-20 at 9 32 59 pm" src="https://user-images.githubusercontent.com/19569343/63351591-1b2baf00-c392-11e9-9227-79428c97fe11.png">

**Comment by JuniperPhoton** [comment]
I really appreciate your work. However the current icon is not suitable for adaptive icon in Android. I may come with up a new icon to do that.
