### ISSUE TITLE
How To Change API Key Of Unsplash?

### ISSUE THREAD

**Issue by bakshinderpreetsingh** [JuniperPhoton/MyerSplash.Android#5]
Do We Need To Change the api key which we get from Unsplash or should we just use the one you used in this project?
if we need to change the api key then where should we insert the api key which we obtained from unsplash?....

**Comment by JuniperPhoton** [comment]
You can see there is a line in app's `build.gradle`: 

`buildConfigField 'String', "UNSPLASH_APP_KEY", "\"" + unsplashKey + "\""`

You should insert you own api key in `local.properties` file:

`unsplashKey=xxxxx`

**Comment by bakshinderpreetsingh** [comment]
Thanks!...

**Comment by JuniperPhoton** [comment]
It doesn't matter... It's used when you about to implement the login feature.

**Comment by bakshinderpreetsingh** [comment]
One Last question!....does the app has UTM tracking on links to Unsplash already setted up?...if yes then how can i show this to unsplash or take a screenshot so that i can show unsplash that i have setup UTM tracking links?.....Really Appreciate it!
