### ISSUE TITLE
[功能请求] Android 端自动更换壁纸

### ISSUE THREAD

**Issue by Steve-Mr** [JuniperPhoton/MyerSplash.Android#7]
MyerSplash UWP 里每日自动更换壁纸的功能很棒（挑选的壁纸真的很好看），不知道有没有可能将来把这个功能带到 Android 端？

**Comment by JuniperPhoton** [comment]
Android 应该还是有 API 实现这个，但是考虑到 Android 下定时服务的不可靠性，暂时没这个计划。
